apiVersion: v1
kind: Service
metadata:
  name: weather-app-nodeport
  namespace: weather-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
  selector:
    app: weather-app 