name: Build and Push Docker Image

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'weather-app/**'
      - '.github/workflows/build-app.yml'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name cst8918acr

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./weather-app
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/weather-app:${{ github.sha }}
            ${{ secrets.ACR_LOGIN_SERVER }}/weather-app:latest 