name: Complete CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'modules/**'
      - 'environments/**'
      - 'weather-app/**'
      - '.github/workflows/complete-pipeline.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'modules/**'
      - 'environments/**'
      - 'weather-app/**'
      - '.github/workflows/complete-pipeline.yml'

permissions:
  id-token: write
  contents: read

jobs:
  # Step 1: Static Analysis
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.44.1

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: modules

      - name: Terraform Init - Network Module
        run: terraform init
        working-directory: modules/network
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: modules/network
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: TFLint
        run: |
          tflint --init
          tflint --recursive
        working-directory: modules

      - name: tfsec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: modules

  # Step 2: Build Application
  build-app:
    runs-on: ubuntu-latest
    needs: static-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local only)
        uses: docker/build-push-action@v5
        with:
          context: ./weather-app
          platforms: linux/amd64
          push: false
          tags: weather-app:latest

  # Step 3: Terraform Apply (for push to main)
  terraform-apply-dev:
    runs-on: ubuntu-latest
    needs: [static-analysis, build-app]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock-timeout=300s
        working-directory: environments/dev
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  terraform-apply-test:
    runs-on: ubuntu-latest
    needs: terraform-apply-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init
        working-directory: environments/test
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock-timeout=300s
        working-directory: environments/test
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  terraform-apply-prod:
    runs-on: ubuntu-latest
    needs: terraform-apply-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init
        working-directory: environments/prod
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock-timeout=300s
        working-directory: environments/prod
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # Step 5: Deploy Application
  deploy-app-test:
    runs-on: ubuntu-latest
    needs: terraform-apply-test
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check AKS cluster status
        run: |
          echo "Checking AKS cluster status..."
          az aks show --resource-group cst8918-final-project-group-1 --name test-aks --query "powerState.code" -o tsv || echo "Cluster not found or not accessible"
        continue-on-error: true

      - name: Get AKS credentials
        run: |
          echo "Getting AKS credentials..."
          az aks get-credentials --resource-group cst8918-final-project-group-1 --name test-aks --overwrite-existing
        continue-on-error: true

      - name: Check kubectl connectivity
        run: |
          echo "Testing kubectl connectivity..."
          kubectl cluster-info || echo "Cannot connect to cluster"
          kubectl get nodes || echo "Cannot get nodes"
        continue-on-error: true

      - name: Deploy to test environment
        run: |
          echo "Applying Kubernetes manifests..."
          kubectl apply -f environments/test/weather-service.yaml --dry-run=client
          kubectl apply -f environments/test/weather-service.yaml
          
          echo "Waiting for deployment to be ready..."
          kubectl rollout status deployment/weather-app -n default --timeout=300s || {
            echo "Deployment failed, checking pod status..."
            kubectl get pods -n default -l app=weather-app
            kubectl describe deployment weather-app -n default
            exit 1
          }
          
          echo "Deployment successful!"
          kubectl get services -n default

  deploy-app-prod:
    runs-on: ubuntu-latest
    needs: terraform-apply-prod
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check AKS cluster status
        run: |
          echo "Checking AKS cluster status..."
          az aks show --resource-group cst8918-final-project-group-1 --name prod-aks --query "powerState.code" -o tsv || echo "Cluster not found or not accessible"
        continue-on-error: true

      - name: Get AKS credentials
        run: |
          echo "Getting AKS credentials..."
          az aks get-credentials --resource-group cst8918-final-project-group-1 --name prod-aks --overwrite-existing
        continue-on-error: true

      - name: Check kubectl connectivity
        run: |
          echo "Testing kubectl connectivity..."
          kubectl cluster-info || echo "Cannot connect to cluster"
          kubectl get nodes || echo "Cannot get nodes"
        continue-on-error: true

      - name: Deploy to production environment
        run: |
          echo "Applying Kubernetes manifests..."
          kubectl apply -f environments/prod/weather-service.yaml --dry-run=client
          kubectl apply -f environments/prod/weather-service.yaml
          
          echo "Waiting for deployment to be ready..."
          kubectl rollout status deployment/weather-app -n default --timeout=300s || {
            echo "Deployment failed, checking pod status..."
            kubectl get pods -n default -l app=weather-app
            kubectl describe deployment weather-app -n default
            exit 1
          }
          
          echo "Deployment successful!"
          kubectl get services -n default 