name: Static Analysis

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'modules/**'
      - 'environments/**'
      - '.github/workflows/static-analysis.yml'

jobs:
  terraform-static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.5.0"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.44.1

      - name: Terraform Format Check
        run: |
          terraform fmt -check -recursive
        working-directory: .

      - name: Terraform Validate (Modules Only)
        run: |
          # Validate modules without backend
          for module in modules/*/; do
            if [ -f "$module/main.tf" ]; then
              echo "Validating module: $module"
              cd "$module"
              terraform init -backend=false
              terraform validate
              cd ../..
            fi
          done

      - name: TFLint
        run: |
          tflint --init
          tflint --recursive

      - name: tfsec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: .
          format: sarif
          soft_fail: true

      - name: Upload tfsec results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tfsec-results
          path: tfsec.sarif 