name: Static Analysis

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'modules/**'
      - 'environments/**'
      - '.github/workflows/static-analysis.yml'

jobs:
  terraform-static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.44.1

      - name: Setup tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: .

      - name: Terraform Format Check
        run: |
          terraform fmt -check -recursive
        working-directory: .

      - name: Terraform Validate
        run: |
          for dir in environments/*/; do
            if [ -f "$dir/main.tf" ]; then
              echo "Validating $dir"
              terraform init -backend=false $dir
              terraform validate $dir
            fi
          done

      - name: TFLint
        run: |
          tflint --init
          tflint --recursive

      - name: tfsec Security Scan
        run: |
          tfsec --format sarif --out tfsec.sarif --soft-fail
        continue-on-error: true

      - name: Upload tfsec results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tfsec-results
          path: tfsec.sarif 